spring:
  profiles:
    active: EN, qa
math:
  username: MatheeshYML
  password: PassYML
  permission: AllowedYML

---
spring:
  profiles: qa
math:
  username: MatheeshYMLqa
  password: PassYMLqa
  permission: AllowedYMLqa
